### ISSUE TITLE
Invalid `main` field in package.json

### ISSUE THREAD

**Issue by jacobq** [airportyh/fireworm#13]
I stumbled across this and figured I ought to be a good citizen and at least create an issue.

> [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/me/tmp/ember-did-resize-modifier/node_modules/fireworm/package.json' of 'fireworm.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

`$ cat node_modules/fireworm/package.json `
```json
{
  "name": "fireworm",
  "version": "0.7.1",
  "description": "A crawling file watcher.",
  "main": "fireworm.js",
  "...": "..."
}
```

I think the error message would go away if you set `"main": "index.js"` or omitted it entirely.

**Comment by airportyh** [comment]
Thanks. Just fixed and published an update https://github.com/airportyh/fireworm/commit/a0da5221eafb8253553cc4f6c59f8ba91421f6fc.
